### ISSUE TITLE
Error in "SaveParamsAsNIfTI" 

### ISSUE THREAD

**Issue by alfredomp** [CyclotronResearchCentre/NODDI_singularity#2]
First of all, thank you for making this Singularity container available. It helps a lot running NODDI in machines that don't have Matlab, and also to run multiple cases in parallel using a single command line.

I am getting the following error (see below) at the end of the pipeline. The file `FittedParams.mat` has been created, which is what takes a lot of time, but the final results are not being saved. 

Questions:
1. Is there a way to run only the last command: `SaveParamsAsNIfTI('FittedParams.mat', 'NODDI_roi.mat', 'brain_mask.hdr', 'example')`
2. How can I fix this issue?

**Comand line:**
```
singularity run --cleanenv \
    --bind /data_noddi/:/In_fold \
    /noddi/noddi-singularity_1.0.1.sif \
    /In_fold/dti.nii \
    /In_fold/brain_mask.nii \
    /In_fold/NODDI_roi.mat \
    /In_fold/dti.bval \
    /In_fold/dti.bvec \
    /In_fold/FittedParams.mat \
    /in_fold/noddi
```

**Error:**
...
Fitting voxel 183205
Elapsed time is 109087.493633 seconds.
loading the fitted parameters from : /In_fold/FittedParams.mat
loading the roi from : /In_fold/NODDI_roi.mat
loading the target volume : /In_fold/brain_mask.nii
converting the fitted parameters into volumetric maps ...
Saving the volumetric maps of the fitted parameters ...
Error: No such file or directory
There was a problem writing to the header of
  "/in_fold/noddi_ficvf.nii"
Error using nifti/create (line 26)
Unable to write header for "/in_fold/noddi_ficvf.nii".

Error in SaveAsNIfTI (line 33)

Error in SaveParamsAsNIfTI (line 161)

Error in ss_noddi (line 63)
```

**Comment by ChristophePhillips** [comment]
Hmm, I am not 100% familiar with the inner working of the Singularity container. Still I see that on the last line of your command, you write `/in_fold/` with a lower `i` while all the other lines have `/In_fold/` with an upper `I`. This quite fit your error message and the timing of the problem... thus could this be a simple folder naming issue?

If this is not the problem, maybe @MartinGrignard or @SherS2 have some deeper idea.

**Comment by SiyaMRPhy** [comment]
@alfredomp I will have a look at it and let you know

**Comment by alfredomp** [comment]
@ChristophePhillips thank you, I didn’t notice it. I actually copy/pasted from the example in the `Readme.md` I’ll create a PR with the change. The good news it that the FittedParams.mat file was already created so I can rexecute and get the results without waiting for the main processing to finish.

**Comment by ChristophePhillips** [comment]
Did it fix your problem ?

To keep track of things, the PR is https://github.com/CyclotronResearchCentre/NODDI_singularity/pull/3
And I did a 2nd commit for the same typo in the example code directly underneath (for the NODDI example dataset).

**Comment by alfredomp** [comment]
I’ll test and let you know.

**Comment by alfredomp** [comment]
It works. It took 6 days to complete the task but it did it. Thank you!
SIde question: would it be possible to create a container that includes the parallel processing?

**Comment by SiyaMRPhy** [comment]
parallel processing would require an additional MatLab licence.
One could use the container to process more subjects in parallel on clusters (or in a PC depending on the RAM).

**Comment by ChristophePhillips** [comment]
@alfredomp , on which sort of hardware did you run your data processing? And how many subjects did you process altogether ?

As @SherS2 said, you could parallelize the processing of multiple subjects, if your hardware can handle the workload...

**Comment by alfredomp** [comment]
@ChristophePhillips I ran that one subject in a machine with 64 cores and 64GB of RAM using the singularity container. The log file shows `807287 of voxels to fit`, which I think explains why it took so long.

I then moved to using a cluster with parallel processing (8 cores) using the Matlab code. A single subject took between 2 and 3 days to run, depending on the number of voxels to fit. I ran a total of 26 subjects in ~9 days as I had ~8 subjects running in parallel at a given time. I could have ran all the subjects in the machine I ran the first case but it was needed for other processing.

Side note: I had to comment out some code in the original Matlab code so that the Matlab runs `matlab -nodesktop`. There is a library that they use to show a progress bar that crashes the code if no gui is used. Do you have the matlab code that was wrapped in the singularity container? Also, if you have instructions on how to create the container I might be able to create one with the parallel processing library included.

**Comment by ChristophePhillips** [comment]
As far as I can tell from the code in [`compile_ss_noddi.m`](https://github.com/CyclotronResearchCentre/NODDI_singularity/blob/main/ss_noddi/compile_ss_noddi.m), @SherS2 used `NODDI_toolbox_v1.05`.

No idea how parallel processing (fitting multiple voxels at the same time) will work out with the Matlab compiled standalone placed in a Syngularity container...

**Comment by SiyaMRPhy** [comment]
This tool was designed for users to run the code on clusters without a Matlab licence.
