### ISSUE TITLE
Error running singularity NODDI

### ISSUE THREAD

**Issue by Bea9619** [CyclotronResearchCentre/NODDI_singularity#4]
Dear developers,
I'm running the containerized version of NODDI toolbox following the instructions reported here in the Read Me section. I tried first with the NODDI example dataset, as follows:

_singularity run --cleanenv \
    --bind /path/to/NODDI_example_dataset:/In_fold \
    /path/to/noddi-singularity.sif \
    /In_fold/NODDI_DWI.hdr \
    /In_fold/roi_mask.hdr \
    /In_fold/NODDI_roi.mat \
    /In_fold/NODDI_protocol.bval \
    /In_fold/NODDI_protocol.bvec \
    /In_fold/FittedParams.mat
    /In_fold/example_ 

The container starts to fit every voxel in the ROI mask, however at the end of fitting, this error comes:

_Fitting voxel 178921
Fitting voxel 178922
Fitting voxel 178923
Fitting voxel 178924
Elapsed time is 61520.966940 seconds.
Not enough input arguments.

Error in ss_noddi (line 63)

MATLAB:minrhs

/In_fold/example
bash: /In_fold/example: No such file or directory_

However, at line 63 of ss_noddi.m there's only a commented line: % model 
This happened both with the example dataset and my data. I controlled the inputs several times but all seems correct
How can I solve the problem?
Many thanks in advance

Beatrice

**Comment by ChristophePhillips** [comment]
As fixed here above by @chrisrj in commit 332c4ff, the problem stemmed from a missing `\` on 2 lines.

**Comment by Bea9619** [comment]
Thanks!
